<?php
    $projectID       = !empty( $data[0] ) ? $data[0] : "";
    $configurationID = !empty( $data[1] ) ? $data[1] : "";
    $project         = $this->get_project( $projectID );
    $configurations  = $this->get_project_configurations( $projectID );
?>

<div class="container">
    <div class="container-title">Project <?= $project->name ?> configurations</div>
    <div class="container-menu">
        <a href="" onclick="goBack()">Ga terug</a>
        <a href="<?= BASE_PATH; ?>projects/index">Projects</a>
        <a href="<?= BASE_PATH; ?>projects/new">Project toevoegen</a>
        <a href="<?= BASE_PATH ?>projects/new-configuration/<?= $projectID ?>">new configuration</a>
    </div>
</div>

<?php if( !empty( $configurationID ) ): ?>
    <div class="branch-container">
        <form action="<?= BASE_PATH ?>projects/new-branch" method="post">
            <fieldset>
                <legend>Enter a branch name</legend>
                <input type="hidden" name="projectID" value="<?= $projectID ?>">
                <input type="hidden" name="configurationID" value="<?= $configurationID ?>">
                <input type="text" name="branch" value="">
                <input type="submit" name="submit" value="add">
            </fieldset>
        </form>
    </div>
<?php endif; ?>



<?php if( !empty( $projectID ) && !empty( $configurations ) ): ?>

    <div class="projects">
        <table>
            <tr>
                <th>Configuration number</th>
                <th>Version</th>
                <th>Branch</th>
                <th>End user</th>
                <th>Created</th>
                <th></th>
            </tr>

            <?php foreach( $configurations as $configuration ): ?>
                <tr>
                    <td><span><?= $configuration['hash'] ?></span></td>
                    <td><span><?= $configuration['version'] ?></span></td>
                    <td><span><?= $configuration['branch'] ?></span></td>
                    <td><span><?= $configuration['end_user_type'] ?></span></td>
                    <td><span><?= $configuration['created_at'] ?></span></td>
                    <td>
                        <span><a href="<?= BASE_PATH ?>projects/configurations/test/<?= $configuration['id'] ?>">test</a></span>
                        <span><a href="<?= BASE_PATH ?>projects/configurations/<?= $projectID ?>/<?= $configuration['id'] ?>">branch</a></span>
                        <span><a href="<?= BASE_PATH ?>projects/configurations/settings/<?= $configuration['id'] ?>">settings</a></span>
                    </td>
                </tr>
            <?php endforeach; ?>

        </table>
    </div>

<?php elseif( empty( $projectID ) ): ?>
    <div class="display-message">Kon het project niet vinden, selecteer een ander project.</div>
<?php elseif( empty( $configurations ) ): ?>
    <div class="display-message">Dit project heeft nog geen configuraties, maak een nieuwe aan boven aan de pagina.</div>
<?php endif; ?>