<?php

use app\core\traits\ProjectConfiguration as Pconfig;

$projectID         = !empty( $data[0] ) ? $data[0] : "";
$configurationID   = !empty( $data[1] ) ? $data[1] : "";
$project           = $this->get_project( $projectID );
$configurations    = $this->get_project_configurations( $projectID );
$configuration_map = $this->get_configuration_map( $projectID );
?>

<div class="container">
    <div class="container-title">Project <?= $project->name ?> configurations</div>
    <div class="container-menu">
        <a href="" onclick="goBack()">Ga terug</a>
        <a href="<?= BASE_PATH; ?>projects/index">Projects</a>
        <a href="<?= BASE_PATH; ?>projects/new">Project toevoegen</a>
        <a href="<?= BASE_PATH ?>projects/new-configuration/<?= $projectID ?>">new configuration</a>
    </div>
</div>

<?php if( !empty( $configurationID ) ): ?>
    <div class="branch-container">
        <form action="<?= BASE_PATH ?>projects/new-branch" method="post">
            <fieldset>
                <legend>Enter a branch name</legend>
                <input type="hidden" name="projectID" value="<?= $projectID ?>">
                <input type="hidden" name="configurationID" value="<?= $configurationID ?>">
                <input type="text" name="branch" value="">
                <input type="submit" name="submit" value="add">
            </fieldset>
        </form>
    </div>
<?php endif; ?>



<?php if( !empty( $projectID ) && !empty( $configurations ) ): ?>

    <div class="configurations">

        <div class="base">
            <h1>Base</h1>

    <?php
        foreach( $configurations as $configuration ):
            if( $configuration['branch'] === "master" ):
    ?>
            <div class="master">
                <div class="master-branch">
                    <?= $configuration['branch'] ?>
                    <?= $configuration['version'] ?>
                    <?= $configuration['end_user_type'] ?>
                    <?= $configuration['hash'] ?>
                    <?= $configuration['created_at'] ?>

                    <a href="<?= BASE_PATH ?>projects/configurations/test/<?= $configuration['id'] ?>">test</a>
                    <a href="<?= BASE_PATH ?>projects/configurations/<?= $projectID ?>/<?= $configuration['id'] ?>">branch</a>
                    <a href="<?= BASE_PATH ?>projects/configurations/settings/<?= $configuration['id'] ?>">settings</a>

                </div>

            <?php
                $sub_branches = $this->get_project_branches( $projectID );
                foreach( $sub_branches as $sub_branch ):
                    var_dump( $sub_branch );
                endforeach;

            ?>

            </div>

            <?php
            endif;
        endforeach;
        ?>

        </div>

    </div>


<?php elseif( empty( $projectID ) ): ?>
    <div class="display-message">Kon het project niet vinden, selecteer een ander project.</div>
<?php elseif( empty( $configurations ) ): ?>
    <div class="display-message">Dit project heeft nog geen configuraties, maak een nieuwe aan boven aan de pagina.</div>
<?php endif; ?>