<?php $projects = $this->get_all_projects_public(); ?>

<div class="container">
    <div class="container-title">Projects</div>
    <div class="container-menu">
        <a href="" onclick="goBack()">Ga terug</a>
        <a href="<?= BASE_PATH; ?>projects/new">Project toevoegen</a>
    </div>
</div>

<div class="projects">
    <table>
        <tr>
            <th>Project</th>
            <th>Description</th>
            <th>Model</th>
            <th>Calculator</th>
            <th>Info</th>
            <th>Created</th>
            <th></th>
        </tr>
        <?php foreach( $projects as $project ): ?>
            <tr>
                <td><?= $project->name ?></td>
                <td><?= $project->description ?></td>
                <td>No</td>
                <td>No</td>
                <td>my project | new</td>
                <td><?= $project->created_at ?></td>
                <td>
                    <a href="<?= BASE_PATH ?>projects/settings">settings</a>
                    <a href="<?= BASE_PATH ?>projects/index/<?= $project->id ?>">configurations</a>
                    <a href="<?= BASE_PATH ?>projects/edit">edit</a>
                </td>
            </tr>
            <?php if( !empty( $data ) && (int) $data === $project->id ): $configurations = $this->get_project_configurations( $project->id ); ?>
                <tr>
                    <td colspan="7">
                        <div class="configurations">
                            <p>
                                Showing configuration(s) for project <?= $project->name ?>
                            </p>
                            <a href="<?= BASE_PATH ?>projects/index">close</a>
                            <a href="<?= BASE_PATH ?>projects/new-configuration/<?= $project->id ?>">new configuration</a>
                            <?php if( !empty( $configurations ) ): ?>
                                <table>
                                    <tr>
                                        <th>Configuration number</th>
                                        <th>Version</th>
                                        <th>Branch</th>
                                        <th>End user</th>
                                        <th>Created</th>
                                        <th></th>
                                    </tr>
                                    <?php foreach( $configurations as $configuration ): ?>
                                    <tr>
                                        <td><?= $configuration['hash'] ?></td>
                                        <td><?= $configuration['version'] ?></td>
                                        <td><?= $configuration['branch'] ?></td>
                                        <td><?= $configuration['end_user_type'] ?></td>
                                        <td><?= $configuration['created_at'] ?></td>
                                        <td>
                                            <a href="<?= BASE_PATH ?>configurations/edit/<?= $configuration['id'] ?>">edit</a>
                                            <a href="<?= BASE_PATH ?>configurations/test/<?= $configuration['id'] ?>">test</a>
                                            <a href="<?= BASE_PATH ?>configurations/settings/<?= $configuration['id'] ?>">settings</a>
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>
                                </table>
                            <?php else: ?>
                                <div class="configurations-empty">
                                    No configrations found, please create a new one.
                                </div>
                            <?php endif; ?>
                        </div>
                    </td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
    </table>
</div>
