<?php $projects = $this->get_all_projects_public(); ?>

<div class="container">
    <div class="container-title">Projects</div>
    <div class="container-menu">
        <a href="" onclick="goBack()">Ga terug</a>
        <a href="<?= BASE_PATH; ?>projects/new">Project toevoegen</a>
    </div>
</div>

<div class="projects">
    <table>
        <tr>
            <th>Project</th>
            <th>Description</th>
            <th>Model</th>
            <th>Calculator</th>
            <th>Info</th>
            <th>Created</th>
            <th></th>
        </tr>
        <?php foreach( $projects as $project ): ?>
            <tr>
                <td><span><?= $project->name ?></span></td>
                <td><span><?= $project->description ?></span></td>
                <td><span>No</span></td>
                <td><span>No</span></td>
                <td><span>my project | new</span></td>
                <td><span><?= $project->created_at ?></span></td>
                <td>
                    <span><a href="<?= BASE_PATH ?>projects/settings">settings</a></span>
                    <span><a href="<?= BASE_PATH ?>projects/configurations/<?= $project->id ?>">configurations</a></span>
                    <span><a href="<?= BASE_PATH ?>projects/edit">edit</a></span>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
