<?php

namespace web\pages\login;

?>

<div class="login">
    <div class="loginTitle">
        Login
    </div>
        <form action="" method="POST" id="login">
            <div class="loginBox">
                <div class="loginLeft"><span id="email">Email</span></div>
                <div class="loginRight">
                    <input type="email" name="email" placeholder="Your email address">
                </div>
            </div>
            <div class="loginBox">
                <div class="loginLeft"><span id="password">Password</span>
                </div>
                <div class="loginRight">
                    <input type="password" name="password" placeholder="Your password">
                </div>
            </div>
            <div class="loginBox">
                <div class="loginSubmit">
                    <input type="submit" name="loginSubmit" value="Login">
                </div>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">

    $('#login').submit(function(e) {

        e.preventDefault();

        var url = <?= ROOT_DIRECTORY . DIRECTORY_SEPARATOR . APP_DIR . DIRECTORY_SEPARATOR . "app" . DIRECTORY_SEPARATOR . "ajax" . DIRECTORY_SEPARATOR . "login" . DIRECTORY_SEPARATOR . "login.php"; ?>;

        $.ajax({
            type: 'post',
            url: url,
            data: $('#login').serialize(),
            success: function () {
                alert('form was submitted');
            }
        });

    });

</script>
