<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="keywords" content="">
    <meta name="robots" content="nofollow">
    <meta property="og:title" content="Control Management System">
    <meta property="og:type" content="website">
    <meta property="og:description" content="">
    <meta property="og:url" content="">
    <meta property="og:image" content="">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Raleway%7cPassion+One%7cWork+Sans%7cRoboto+Condensed:400" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="public/css/style.min.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="../src/js/chosen.jquery.min.js"></script>
    <title>Hospitium</title>
</head>
<body>
<div class="se-pre-con">
    <div class="se-pre-con-txt">
            <span>
                <img src="public/img/icons/gears.gif?<?= uniqid() ?>">
                <br>
                Loading, please wait...
            </span>
    </div>
</div>

<div class="header">
    <div class="header-navigation dropdown">
        <button onclick="menuDropDown()" class="dropbtn"></button>
        <div id="myDropdown" class="dropdown-content">
            <a href="/home">Home</a>
            <a href="/projects">Projects</a>
            <a href="/manual">Manual</a>
            <a href="/users">Users</a>
            <a href="/contact">Contact</a>
        </div>
    </div>
    <div class="header-title">Blueberry</div>
</div>